name: Docker Image CI

on:
  push:
    branches: [ 0.15 ]
  pull_request:
    branches: [ 0.15 ]

jobs:

  build:

    runs-on: ubuntu-latest
  steps:
    - name: Build docker images
      run: docker build -t local < Dockerfile
    - name: Run tests
      run: docker run -it -v $PWD:/srv -w/srv local make test
